"""add user group and role

Revision ID: 97a86b209bc1
Revises: ee07542f6c53
Create Date: 2025-12-21 19:12:58.979775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a86b209bc1'
down_revision: Union[str, Sequence[str], None] = 'ee07542f6c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_head_student', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_head_student')
    op.drop_column('users', 'group_number')
    # ### end Alembic commands ###
