"""add admin_message_id

Revision ID: ee07542f6c53
Revises: 59e1544c328e
Create Date: 2025-12-21 14:13:22.626850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee07542f6c53'
down_revision: Union[str, Sequence[str], None] = '59e1544c328e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('admin_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'admin_message_id')
    # ### end Alembic commands ###
